name: notiyou
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  go_router: ^14.3.0
  kakao_flutter_sdk: ^1.9.6 # 카카오 로그인 SDK
  shared_preferences: ^2.2.2
  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.2
  supabase_flutter: ^2.8.0
  intl: ^0.17.0
  flutter_native_splash: ^2.4.3
  app_links: ^3.5.0
  crypto: ^3.0.6
  encrypt: ^5.0.3
  meta: ^1.15.0
  firebase_core: ^3.11.0
  firebase_messaging: ^15.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/sample-logo.png
